file_path {
    workdir = ./
    cora_content = ${file_path.workdir}cora/cora.content
    cora_cite = ${file_path.workdir}cora/cora.cites
    HT_path = ${file_path.workdir}ht/
    result_path = ${file_path.workdir}result/
    pubmed_paper = ${file_path.workdir}pubmed-data/Pubmed-Diabetes.NODE.paper.tab
    pubmed_cites = ${file_path.workdir}pubmed-data/Pubmed-Diabetes.DIRECTED.cites.tab
}


setting {
    num_layers = 2
    hidden_emb_size = 64
    feature_size = 25
    hidden_emb_size_after_graphsage = 64
    num_labels = 2
}
